<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "backend_ajax"
 *
 * Auto generated by Extension Builder 2016-02-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'TYPO3 Backend AJAX example',
    'description' => 'Example of AJAX for TYPO3 Backend!',
    'category' => 'module',
    'author' => 'Nirmalya Mondal',
    'author_email' => 'typo3india@gmail.com',
    'author_company' => 'https://typo3nirmalya.blogspot.in/',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0',
            'extbase' => '7.6.0',
            'fluid' => '7.6.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
