<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "typo3_scorm"
 *
 * Auto generated by Extension Builder 2015-04-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'SCORM Integration',
	'description' => 'SCORM Integration with Typo3.',
	'category' => 'module',
	'author' => 'Nirmalya Mondal',
	'author_company' => 'typo3! GbR',
	'author_email' => 'typo3india@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '6.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);