<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pim_ckeditor"
 *
 * Auto generated by Extension Builder 2018-06-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'PIM CkEditor ',
    'description' => 'PIM extension for Custom CkEditor.',
    'category' => 'plugin',
    'author' => 'Nirmalya Mondal',
    'author_email' => 'n.mondal@thepimcompany.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.9',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
