<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "typo3_ajax"
 *
 * Auto generated by Extension Builder 2016-02-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Typo3 AJAX Request Response typoscript Based',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Nirmalya Mondal',
	'author_email' => 'typo3india@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2 - 7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);